import "./globals.css";
import Sidebar from "../component/Sidebar";

export const metadata = {
  title: "My Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className="min-h-screen flex flex-col">
        {/* Pastikan Navbar bersifat client component */}
        <Sidebar/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}